//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Login.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DonativosAlimentacion
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "El campo 'Donativos' es obligatorio.")]
        [StringLength(50, ErrorMessage = "El campo 'Donativos' no puede tener más de 50 caracteres.")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "El donativo solo pueden tener letras y espacios")]
        public string Donativo { get; set; }
        [Required(ErrorMessage = "El campo 'Correo' es obligatorio.")]
        [EmailAddress(ErrorMessage = "Por favor, ingresa una dirección de correo electrónico válida.")]
        public string correocomo_fk { get; set; }
        public System.DateTime fecha_donativo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
