//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Login.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.DonativosAlimentacions = new HashSet<DonativosAlimentacion>();
            this.DonativosDineroes = new HashSet<DonativosDinero>();
            this.DonativosProductosPersonales = new HashSet<DonativosProductosPersonale>();
        }

        [Required(ErrorMessage = "El campo 'Correo' es obligatorio.")]
        [EmailAddress(ErrorMessage = "Por favor, ingresa una dirección de correo electrónico válida.")]
        public string correo { get; set; }

        [Required(ErrorMessage = "El campo 'Nombres' es obligatorio.")]
        [StringLength(50, ErrorMessage = "El campo 'Nombres' no puede tener más de 50 caracteres.")]
        public string nombres { get; set; }

        [Required(ErrorMessage = "El campo 'Apellidos' es obligatorio.")]
        [StringLength(50, ErrorMessage = "El campo 'Apellidos' no puede tener más de 50 caracteres.")]
        public string apellidos { get; set; }

        [Required(ErrorMessage = "El campo 'Contraseña' es obligatorio.")]
        [MinLength(6, ErrorMessage = "La contraseña debe tener al menos 6 caracteres.")]
        public string password_usuario { get; set; }

        [Required(ErrorMessage = "El campo 'Dirección de Residencia' es obligatorio.")]
        public string direccion_residencia { get; set; }

        public bool estado_extranjero { get; set; }

        public int RolUsuario_fk { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonativosAlimentacion> DonativosAlimentacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonativosDinero> DonativosDineroes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonativosProductosPersonale> DonativosProductosPersonales { get; set; }
        public virtual Roles_Usuario Roles_Usuario { get; set; }
    }
}
